### ISSUE TITLE
no java error and stuck at finalizing

### ISSUE THREAD

**Issue by yatharthmaheshwari** [D3VL/L3MON#57]
i entered my server and clicked on build apk

then a no java error appeared on left top corner and disappeared

a
![desktop](https://user-images.githubusercontent.com/42062688/75095376-0a1a5f80-55ba-11ea-8eb0-3b19a6dfd796.PNG)
nd then it has been an hour and it shows finalizing .....
it just stuck there loading and loading and building the apk

what do you think should i re-download the java??

JAVA VERSION
![java version](https://user-images.githubusercontent.com/42062688/75103428-7734f180-55c8-11ea-9229-d2e16baf3c59.PNG)

this is the event log:

```
23/02/2020, 03:54:41 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 03:54:26 => ERROR | Build Failed - Java Not Installed

```

i think still there is a apk file made
![apkfile](https://user-images.githubusercontent.com/42062688/75103466-e9a5d180-55c8-11ea-864b-f21254cf3a81.PNG)

**Comment by Jack-Rogers** [comment]
Please click on "Event Log" and see if there are any errors.
Additionally, please run `java -version` and let me know what the output is. 
Cheers!

**Comment by vasuratanpara** [comment]
I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly.

**Comment by blankx** [comment]
installed most current version, running all necessary dependencies still got no java error. stopped index restarted as root found it eliminated the no java error but still didn't finalize.
changed permissions recursively for all restart and synced processes, everything now works as intended.

**Comment by yatharthmaheshwari** [comment]
> I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.

brother, 

> I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.

i am also using openjdk-8  but still stuck on finalizing and also unable to sign the apk so i am using anathor app to sign the apk

**Comment by yatharthmaheshwari** [comment]
can you explain what you did there...

**Comment by yatharthmaheshwari** [comment]
> Please click on "Event Log" and see if there are any errors.
> Additionally, please run `java -version` and let me know what the output is.
> Cheers!

the error is stll there but i found that the apk file is created

**Comment by blankx** [comment]
chmod 777 the whole thing recursively restart as root then pm2 save after sudo pm2 start index.js and everything runs as expected.
At least that's what worked for me. Have the server running for 6+ hours now and the connection remains persistent over WAN

**Comment by blankx** [comment]
I also completely removed all jdk version except for dependancy

**Comment by vasuratanpara** [comment]
> > I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.
> 
> brother,
> 
> > I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.
> 
> i am also using openjdk-8 but still stuck on finalizing and also unable to sign the apk so i am using anathor app to sign the apk

First check that you have JDK and JRE both by "Java -version" and "Javac -version" if both run successful then i can tell you more specifically.

**Comment by yatharthmaheshwari** [comment]
> > > I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.
> > 
> > 
> > brother,
> > > I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.
> > 
> > 
> > i am also using openjdk-8 but still stuck on finalizing and also unable to sign the apk so i am using anathor app to sign the apk
> 
> First check that you have JDK and JRE both by "Java -version" and "Javac -version" if both run successful then i can tell you more specifically

brother check this out
![new java version](https://user-images.githubusercontent.com/42062688/75103977-b85cee00-5628-11ea-8776-cbe5a17dbb3b.PNG)

**Comment by yatharthmaheshwari** [comment]
For some peaple the finalizing is stuck But the apk file is created.
just the difference is that is not signed.

so i found the apk and signed with easy apk tool But still it did'nt work for me.
that means the apk is corrupt
![signing faile](https://user-images.githubusercontent.com/42062688/75106464-f7983880-5642-11ea-9bb7-b8c8bbc45595.PNG)
![signed](https://user-images.githubusercontent.com/42062688/75106468-fa932900-5642-11ea-865b-c40e75686e09.PNG)

**Comment by yatharthmaheshwari** [comment]
this is how i signed the file
>decompile>compile>Sign APK
![apktool](https://user-images.githubusercontent.com/42062688/75106491-51006780-5643-11ea-8848-4646fd2d78f2.PNG)

**Comment by yatharthmaheshwari** [comment]
> I tried on Windows 10. It wasn't working (maybe because I had new JDK 13 was installed). After that I build in Ubuntu 19.10. It was working perfectly. I hosted on AWS EC2 (Ubuntu 18.04 LTS) and tried to build APK after installing openjdk-8. It worked perfectly. So, my final suggestion is use openjdk-8 and you will get success.

Can you show Your java -version

**Comment by yatharthmaheshwari** [comment]
UPDATE:
this is the summary of the things that have happened

ERROR: java not installed and stuck at finalizing

1) used the latest version of L3MON
2) Both Java and javac is installed 
3) node.js is installed 
4) i'm using 

sudo apt-get install openjdk-8-jre (for java)

and

sudo apt-get install openjdk-8-jdk (for javac)


then i found that the build.apk file was created

so i decompiled>compiled>signed the apk

But the apk file does not work so it means it was not created properly and is corrupt.



Here are some important information You might need:

Log Report

23/02/2020, 09:17:08 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 09:17:02 => ERROR | Build Failed - Java Not Installed
23/02/2020, 09:02:21 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 09:02:15 => ERROR | Build Failed - Java Not Installed
23/02/2020, 09:01:15 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.jav
![nodejs2](https://user-images.githubusercontent.com/42062688/75109954-28ca3600-564e-11ea-92c9-d4dd6ca140c9.PNG)
![nodejs3](https://user-images.githubusercontent.com/42062688/75109955-29fb6300-564e-11ea-8b54-0cdbcae70e5a.PNG)
![javac version](https://user-images.githubusercontent.com/42062688/75109956-2a93f980-564e-11ea-9303-f62643589d39.PNG)
![nodejs1](https://user-images.githubusercontent.com/42062688/75109957-2b2c9000-564e-11ea-9a90-670616b40747.PNG)

**Comment by yatharthmaheshwari** [comment]
![java version](https://user-images.githubusercontent.com/42062688/75109978-5616e400-564e-11ea-8fdd-1491e1b27eb9.PNG)
![new java version](https://user-images.githubusercontent.com/42062688/75109981-59aa6b00-564e-11ea-82d6-2d22420a5e27.PNG)

**Comment by yatharthmaheshwari** [comment]
![signing faile](https://user-images.githubusercontent.com/42062688/75109984-5f07b580-564e-11ea-9464-b0d8cd9ffe67.PNG)

**Comment by blankx** [comment]
K, but you're open jdk version is clearly 11.0.5.
It's been stated multiple times function depends on jdk 8. 
Either remove all traces of 11 or configure 8 to default.

**Comment by Jack-Rogers** [comment]
Thankyou @blankx for helping with this. 
I'm going to close this issue as @blankx is exactly right, install 1.8 and don't use any other version and it'll work

**Comment by yatharthmaheshwari** [comment]
> K, but your open jdk version is clearly 11.0.5.
> It's been stated multiple times function depends on jdk 8.
> Either remove all traces of 11 or configure 8 to default.

![java 8](https://user-images.githubusercontent.com/42062688/75201052-6ed9e380-578d-11ea-97ad-13d1d100947a.PNG)
i think i did updated it

**Comment by yatharthmaheshwari** [comment]
and error is still there
"java not installed"

**Comment by blankx** [comment]
pm2 stop index
Then recursively change all permissions of installation folder to 777 then 
pm2 start index.js
then 
pm2 save

**Comment by yatharthmaheshwari** [comment]
How to do this Man!
**"Then recursively change all permissions of installation folder to 777 then"**

**Comment by yatharthmaheshwari** [comment]
ok, i got this 

`chmod -R ug+rw foldername`

 But what is the folder name here

**Comment by yatharthmaheshwari** [comment]
Can You share your Kali linux version: might be problem with that

**Comment by yatharthmaheshwari** [comment]
> K, but your open jdk version is clearly 11.0.5.
> It's been stated multiple times function depends on jdk 8.
> Either remove all traces of 11 or configure 8 to default.

buddy, please open the issue, becuase still not fixed;
![java 8](https://user-images.githubusercontent.com/42062688/75209394-17933d80-57a4-11ea-98e1-81ca640b9e56.PNG)

this is the new log after setting jdk 8 as defualt.
`25/02/2020, 01:05:47 => SUCCESS | Build Succeded!
25/02/2020, 01:05:42 => ERROR | Build Failed - Java Not Installed
25/02/2020, 01:00:35 => SUCCESS | Build Succeded!
25/02/2020, 01:00:30 => ERROR | Build Failed - Java Not Installed
25/02/2020, 00:58:21 => SUCCESS | Build Succeded!
25/02/2020, 00:58:16 => ERROR | Build Failed - Java Not Installed
24/02/2020, 23:45:22 => SUCCESS | Build Succeded!
24/02/2020, 23:45:17 => ERROR | Build Failed - Java Not Installed
23/02/2020, 09:17:08 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 09:17:02 => ERROR | Build Failed - Java Not Installed
23/02/2020, 09:02:21 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 09:02:15 => ERROR | Build Failed - Java Not Installed
23/02/2020, 09:01:15 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 09:01:08 => ERROR | Build Failed - Java Not Installed
23/02/2020, 03:54:41 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Desktop/lemon/app/factory/sign.jar" "/root/Desktop/lemon/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more
23/02/2020, 03:54:26 => ERROR | Build Failed - Java Not Installed`

**Comment by blankx** [comment]
This is a user issue not a software issue

**Comment by yatharthmaheshwari** [comment]
> This is a user issue not a software issue

Yup! man But i did everything according to the documentation But it still doesn't works.

as you said that i have to give recursive permssion to the installation folder --worked for You but it ain't working for me

**Comment by vd062** [comment]
i was having same problem. I just removed JRE from my path variables and put JDK in path variable.
Did Jdk/bin ,, Jdk/java.exe, and in JAVA_HOME = "../Jdk/" 
I followed this [https://stackoverflow.com/questions/7709041/javac-is-not-recognized-as-an-internal-or-external-command-operable-program-or](url)
